apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    run: random-giphy
  name: random-giphy
  namespace: random-giphy
spec:
  rules:
  - host: random-giphy.arctiqtim.anthos.labs.arctiq.ca
    http:
      paths:
      - backend:
          serviceName: random-giphy
          servicePort: 8080
  tls:
  - hosts:
    - random-giphy.arctiqtim.anthos.labs.arctiq.ca
