apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: registry.arctiqtim.anthos.labs.arctiq.ca/random-giphy/random-giphy
  newTag: v1.1
